CC = gcc

#debug & testing flags
CFLAGS = -Wall -g -O0 -fbuiltin -c -DPCOL_SIM -DDEBUG=0
BFLAGS = -Wall -g -O0 -fbuiltin -DPCOL_SIM -DDEBUG=0

LULU_PCOL_SIM_PATH = /home/andrei/script_Python/lulu_pcol_sim/sim.py
LULU_C_PATH = /home/andrei/script_Python/lulu_c/lulu_c.py
LULU_INSTANCE_FILE = /home/andrei/script_Python/lulu_pcol_sim/input_files/input_ag_decrement.txt

#CFLAGS = -Wall -g -O0 -fbuiltin -c
#BFLAGS = -Wall -g -O0 -fbuiltin

all: build/simulator

clean:
	rm -vf build/*

clean_lulu_autogenerated:
	rm -vf instance.* rules.*

build/simulator: build/simulator.o build/instance.o build/rules.o build/lulu.o
	$(CC) $(BFLAGS) $^ -o $@

build/simulator.o: simulator.c rules_generate instance_generate
	$(CC) $(CFLAGS) simulator.c -o $@

build/instance.o: instance.h instance.c instance_generate
	$(CC) $(CFLAGS) instance.c -o $@

build/lulu.o: lulu.h lulu.c
	$(CC) $(CFLAGS) lulu.c -o $@

build/rules.o: rules.h rules.c rules_generate
	$(CC) $(CFLAGS) rules.c -o $@

rules_generate:
	python $(LULU_PCOL_SIM_PATH) --ruleheader rules

instance_generate:
	python $(LULU_C_PATH) $(LULU_INSTANCE_FILE) instance
