CC = gcc

#debug & testing flags
CFLAGS = -Wall -g -O0 -fbuiltin -c -DPCOL_SIM -DDEBUG=0
BFLAGS = -Wall -g -O0 -fbuiltin -DPCOL_SIM -DDEBUG=0

LULU_PCOL_SIM_PATH = /home/andrei/script_Python/lulu_pcol_sim
LULU_PCOL_SIM = $(LULU_PCOL_SIM_PATH)/sim.py
LULU_C = /home/andrei/script_Python/lulu_c/lulu_c.py
LULU_INSTANCE_FILE = $(LULU_PCOL_SIM_PATH)/input_files/input_ag_decrement.txt

all: build/simulator build/liblulu.a

clean:
	rm -vf build/*

clean_autogenerated_lulu:
	rm -vf instance.* rules.*

build/liblulu.a: build/lulu.o build/rules.o
	ar rcs $@ $^

build/simulator: build/simulator.o build/instance.o build/rules.o build/lulu.o
	$(CC) $(BFLAGS) $^ -o $@

build/simulator.o: simulator.c instance.h rules.h
	$(CC) $(CFLAGS) simulator.c -o $@

build/instance.o: instance.h instance.c rules.h
	$(CC) $(CFLAGS) instance.c -o $@

build/lulu.o: lulu.h lulu.c rules.h
	$(CC) $(CFLAGS) lulu.c -o $@

build/rules.o: rules.h rules.c
	$(CC) $(CFLAGS) rules.c -o $@

rules.h rules.c:
	python $(LULU_PCOL_SIM) --ruleheader rules

instance.h instance.c:
	python $(LULU_C) $(LULU_INSTANCE_FILE) instance
