// vim:filetype=c
/**
 * @file lulu.h
 * @brief Lulu P colony simulator rule types
 * This header defines all of the rule types that are accepted by the simulator.
 * This file was auto-generated by lulu_pcol_sim -gentypes rules.h
 * @author Andrei G. Florea
 * @author Catalin Buiu
 * @date 2016-02-08
 */
#ifndef TYPES_H
#define TYPES_H

#include <stdint.h>
typedef enum _rule_type {
    //non-conditional (single rules)
    RULE_TYPE_NONE = -1,
    RULE_TYPE_EVOLUTION,
    RULE_TYPE_COMMUNICATION,
    RULE_TYPE_EXTEROCEPTIVE,
    RULE_TYPE_TAPE_EVOLUTION,
    RULE_TYPE_TAPE_COMMUNICATION,
    //conditional (pair of rules)
    RULE_TYPE_CONDITIONAL_EVOLUTION_EVOLUTION = 10,
    RULE_TYPE_CONDITIONAL_EVOLUTION_COMMUNICATION,
    //..... will be automatically generated
} rule_type_t;

// the tables are generated according to the order of the rules defined in rule_type_t
rule_type_t lookupFirst[] = {RULE_TYPE_EVOLUTION, RULE_TYPE_EVOLUTION};
rule_type_t lookupSecond[] = {RULE_TYPE_EVOLUTION, RULE_TYPE_COMMUNICATION};

#endif
